apiVersion: v1
kind: Service
metadata:
  name: heuteabstimmung
  labels:
    app: heuteabstimmung
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
  selector:
    app: heuteabstimmung