micronaut:
  application:
    name: heuteabstimmung-app

datasources:
  default:
    driverClassName: org.postgresql.Driver
    username: 'demo'

# https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html#additionalConfig
flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    packages-to-scan:
      - 'com.noser.heuteabstimmung.core.ports.persistence'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

