
datasources:
  default:
    url: jdbc:postgresql://postgresql:5432/heuteabstimmung
    username: heuteabstimmung
    password: irgendwas

flyway:
  datasources:
    default:
      locations:
        - classpath:db/migration
        - classpath:db/migration-prod
      clean-schema: true